version: "3"
services:

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    command: >
      --requirepass redis

  db:
    image: postgres:10.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./.dbdata://var/lib/postgresql/data
    environment:
      - POSTGRES_DB=learn_micro_users
      - POSTGRES_USER=postgres
