POSTGRES_USER: "postgres"
POSTGRES_PASSWORD: "password"
POSTGRES_DB: "users_dev"
APP_DB_USERNAME: "postgres"
APP_DB_PASSWORD: ""
APP_DB_NAME: "learn_micro_users"
APP_RD_ADDRESS: "redis:6379"
APP_RD_AUTH: "password"
APP_RB_DBNAME: "0"
DATABASE_DEV_URL: "postgres://postgres:postgres@users-service-db:5432/users_dev?sslmode=disable"